# coding: UTF-8

# Facebook Messenger & Wit.AI API
ACCESS_TOKEN = "EAAaLkUG4fWQBACit25KQ6Gnd9mV3ZB5m8JnzXEGvXBa0oQojVs297tdhZCaa3tG19dHlQbaSrhXFyzFAz8lGyqmGgQsaMBhrmDYjSlnXFhgEw4cAuuXXH5wZCzttRqPhQH1zTUJ6Lng854U7Ou4OZCCOAJyUq61CxWan7xdpLQZDZD"
VERIFY_TOKEN = "Zch9qvxUHIbwMNohYmI7wKLCgSHVIZJUhFOB9xPcRZmlYuvs14Jrf0Dbw5cUAaOy"
WIT_AI_ACCESS_TOKEN = "VVAI3MDKBZQAWF2DJRORSBCUNW33HP7Z"

# Payloads
GET_STARTED_PAYLOAD = "GET_STARTED_PAYLOAD"
PAYLOAD_PHONE_PRICE = "PHONE_PRICE_"
PAYLOAD_SHOW_HELP = "PAYLOAD_SHOW_HELP"

TELENOR_SUPPORT_PHONE_NUMBER = "+381639000"